// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Button: typeof import('./src/components/CustomEL/Button/index.vue')['default']
    CheckboxBase: typeof import('./src/components/CustomEL/Checkbox/CheckboxBase.vue')['default']
    CheckboxGroup: typeof import('./src/components/CustomEL/Checkbox/CheckboxGroup.vue')['default']
    ColumnDefault: typeof import('./src/components/CustomEL/Table/components/ColumnDefault.vue')['default']
    ColumnOperation: typeof import('./src/components/CustomEL/Table/components/ColumnOperation.vue')['default']
    ColumnRadio: typeof import('./src/components/CustomEL/Table/components/ColumnRadio.vue')['default']
    DatePicker: typeof import('./src/components/CustomEL/DatePicker/DatePicker.vue')['default']
    Dialog: typeof import('./src/components/CustomEL/Dialog/index.vue')['default']
    Divider: typeof import('./src/components/CustomEL/Divider/index.vue')['default']
    Echarts: typeof import('./src/components/Echarts/index.vue')['default']
    EditorImage: typeof import('./src/components/Tinymce/components/EditorImage.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubmenu: typeof import("element-plus/es")["ElSubmenu"];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTimePicker: typeof import("element-plus/es")["ElTimePicker"];
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import("element-plus/es")["ElTree"];
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FlexBox: typeof import('./src/components/FlexBox/index.vue')['default']
    Form: typeof import("./src/components/CustomEL/Form/index.vue")["default"];
    FormBase: typeof import('./src/components/CustomEL/Form/FormBase.vue')['default']
    FormCol: typeof import('./src/components/CustomEL/Form/components/FormCol.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    Icon: typeof import('./src/components/CustomEL/Icon/index.vue')['default']
    Iframe: typeof import('./src/components/Iframe/index.vue')['default']
    Input: typeof import("./src/components/CustomEL/Input/index.vue")["default"];
    InputBase: typeof import('./src/components/CustomEL/Input/InputBase.vue')['default']
    JsonEditor: typeof import('./src/components/JsonEditor/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Page: typeof import('./src/components/CustomEL/Page/index.vue')['default']
    Select: typeof import("./src/components/CustomEL/Select/index.vue")["default"];
    SelectBase: typeof import('./src/components/CustomEL/Select/SelectBase.vue')['default']
    Space: typeof import('./src/components/CustomEL/Space/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Table: typeof import("./src/components/CustomEL/Table/index.vue")["default"];
    TableBase: typeof import('./src/components/CustomEL/Table/TableBase.vue')['default']
    TableColumn: typeof import('./src/components/CustomEL/Table/components/TableColumn.vue')['default']
    Tabs: typeof import('./src/components/CustomEL/Tabs/index.vue')['default']
    Text: typeof import('./src/components/Text/index.vue')['default']
    Tinymce: typeof import('./src/components/Tinymce/index.vue')['default']
    Tooltip: typeof import('./src/components/CustomEL/Tooltip/index.vue')['default']
    UploadBase: typeof import('./src/components/CustomEL/Upload/UploadBase.vue')['default']
  }
}

export { }
